package com.resonolabs.runtime.host;
import android.content.Context; import android.os.Handler; import android.os.Looper; import android.util.Base64;
import org.json.JSONObject; import java.io.InputStream; import java.net.HttpURLConnection; import java.net.URL; import java.nio.charset.StandardCharsets; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicBoolean;
/** Authenticated client for one bounded image inspection. */
public final class RuntimeHandoffClient implements AutoCloseable {
 public interface Callback { void onInspected(JSONObject value); void onFailure(String code, String message); }
 private final ExecutorService worker=Executors.newSingleThreadExecutor(); private final Handler main=new Handler(Looper.getMainLooper()); private final AtomicBoolean closed=new AtomicBoolean();
 public void inspect(Context context,String session,String filename,String mime,String note,byte[] image,Callback callback){ worker.execute(()->request(context.getApplicationContext(),session,filename,mime,note,image,callback)); }
 private void request(Context context,String session,String filename,String mime,String note,byte[] image,Callback callback){ HttpURLConnection connection=null; try{
  if(session==null||session.isBlank()||image==null||image.length==0){ failure(callback,"invalid_handoff","A live Voice session and image are required."); return; }
  String token=new RuntimeSecretStore(context).loadLocalApiToken(); connection=(HttpURLConnection)new URL("http://127.0.0.1:8765/v1/host/direct-handoffs/inspect").openConnection(); connection.setRequestMethod("POST"); connection.setConnectTimeout(1500); connection.setReadTimeout(50000); connection.setDoOutput(true); connection.setFixedLengthStreamingMode(image.length); connection.setRequestProperty("Authorization","Bearer "+token); connection.setRequestProperty("Content-Type",mime); connection.setRequestProperty("X-ReSono-Voice-Session",session); connection.setRequestProperty("X-ReSono-Filename-B64",encoded(filename)); if(note!=null&&!note.isBlank())connection.setRequestProperty("X-ReSono-Handoff-Note-B64",encoded(note)); connection.getOutputStream().write(image);
  int status=connection.getResponseCode(); InputStream source=status>=400?connection.getErrorStream():connection.getInputStream(); JSONObject value=new JSONObject(new String(source==null?new byte[0]:source.readNBytes(262144),StandardCharsets.UTF_8)); if(status>=300){JSONObject error=value.optJSONObject("error"); failure(callback,error==null?"handoff_failed":error.optString("code","handoff_failed"),error==null?"The image could not be handed to Voice.":error.optString("message")); return;} if(!closed.get())main.post(()->callback.onInspected(value));
 }catch(Exception ignored){failure(callback,"runtime_unavailable","The on-device runtime is unavailable.");}finally{if(connection!=null)connection.disconnect();}}
 private static String encoded(String value){return Base64.encodeToString((value==null?"":value).getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);} private void failure(Callback callback,String code,String message){if(!closed.get())main.post(()->callback.onFailure(code,message));} @Override public void close(){if(closed.compareAndSet(false,true))worker.shutdownNow();}
}
